// <auto-generated />
using System;
using GameGenesisApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameGenesisApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230515144342_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasketProduct", b =>
                {
                    b.Property<int>("BasketsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("BasketsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("BasketProduct");
                });

            modelBuilder.Entity("GameGenesisApi.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("GameGenesisApi.Models.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("GameGenesisApi.Models.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Librarys");
                });

            modelBuilder.Entity("GameGenesisApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GameGenesisApi.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategorys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Les jeux d'action mettent l'accent sur les défis physiques, y compris la coordination œil-main et les temps de réaction.",
                            Name = "Action "
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ces jeux mettent souvent l'accent sur l'exploration, la résolution de problèmes, l'interaction avec l'environnement et les personnages non joueurs.",
                            Name = "Aventure "
                        },
                        new
                        {
                            Id = 3,
                            Description = " Dans ces jeux, les joueurs assument le rôle d'un personnage, souvent dans un cadre fantastique, et prennent des décisions qui affectent le déroulement de l'histoire.",
                            Name = "RPG (Role-Playing Games) "
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ces jeux tentent de simuler la réalité. Cela peut aller de la gestion d'une ferme à la conduite d'un avion.",
                            Name = "Simulation "
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ces jeux exigent que le joueur pense et planifie stratégiquement pour atteindre la victoire. Ils peuvent être en temps réel ou tour par tour.",
                            Name = "Stratégie "
                        },
                        new
                        {
                            Id = 6,
                            Description = "Ces jeux mettent l'accent sur la résolution de problèmes.",
                            Name = "Puzzle "
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ces jeux simulent des sports réels comme le football, le basket-ball, etc. ",
                            Name = "Sport "
                        },
                        new
                        {
                            Id = 8,
                            Description = " Ces jeux impliquent généralement des courses de véhicules contre des adversaires ou contre le temps.",
                            Name = "Course "
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ces jeux mettent l'accent sur la survie du joueur dans un environnement effrayant, généralement avec des ressources limitées.",
                            Name = "Horreur "
                        },
                        new
                        {
                            Id = 10,
                            Description = "Dans ces jeux, deux équipes s'affrontent dans une arène. Chaque joueur contrôle un seul personnage avec des compétences uniques. ",
                            Name = "MOBA "
                        },
                        new
                        {
                            Id = 11,
                            Description = "Ce sont des RPG joués en ligne avec un grand nombre de personnes. ",
                            Name = "MMORPG"
                        },
                        new
                        {
                            Id = 12,
                            Description = " Il s'agit d'un genre de jeu en ligne où un grand nombre de joueurs se bat pour être le dernier survivant.",
                            Name = "Battle Royale "
                        },
                        new
                        {
                            Id = 13,
                            Description = "Ces jeux impliquent principalement de naviguer le personnage du joueur à travers divers obstacles.",
                            Name = "Plateforme "
                        },
                        new
                        {
                            Id = 14,
                            Description = "Ce sont des jeux généralement caractérisés par des niveaux générés aléatoirement et une mort permanente. ",
                            Name = "Roguelike "
                        },
                        new
                        {
                            Id = 15,
                            Description = "Ce sont des jeux d'action vus à la première personne où le joueur utilise des armes à feu et combat des ennemis.",
                            Name = "FPS"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Semblables aux FPS, mais vus à la troisième personne, ce qui donne au joueur une vision plus large de l'environnement du jeu.",
                            Name = "TPS "
                        },
                        new
                        {
                            Id = 17,
                            Description = "Dans ces jeux, un personnage se bat contre un grand nombre d'ennemis. Ces jeux sont souvent coopératifs.",
                            Name = "Beat 'em up / Brawler"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Ces jeux encouragent le joueur à éviter les ennemis plutôt que de les affronter directement.",
                            Name = "Stealth "
                        },
                        new
                        {
                            Id = 19,
                            Description = "Ce genre de jeux met l'accent sur la survie. Le joueur commence généralement avec un minimum de ressources et doit collecter des ressources et des objets tout en évitant, ou en confrontant, les menaces.",
                            Name = "Survival "
                        },
                        new
                        {
                            Id = 20,
                            Description = "Ce sont des jeux qui impliquent des actions simples et répétitives, comme cliquer sur l'écran, pour gagner des points et progresser dans le jeu. ",
                            Name = "Idle / Clicker / Incremental "
                        },
                        new
                        {
                            Id = 21,
                            Description = "Ces jeux mettent l'accent sur la musique et exigent que les joueurs appuient sur des boutons en rythme avec la musique.",
                            Name = "Rythme "
                        },
                        new
                        {
                            Id = 22,
                            Description = " Il s'agit d'un genre de jeu narratif, généralement basé sur du texte, où les joueurs lisent une histoire et font parfois des choix qui affectent le déroulement de l'histoire.",
                            Name = "Visual Novel"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Ces jeux permettent aux joueurs d'interagir avec l'environnement du jeu de manière créative et sans objectif précis.",
                            Name = "Sandbox "
                        },
                        new
                        {
                            Id = 24,
                            Description = " Dans ces jeux, les joueurs placent des tours ou des unités défensives pour arrêter les vagues d'ennemis qui avancent sur un chemin prédéfini.",
                            Name = "Tower Defense"
                        });
                });

            modelBuilder.Entity("GameGenesisApi.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("GameGenesisApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LibraryProduct", b =>
                {
                    b.Property<int>("LibrariesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("LibrariesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("LibraryProduct");
                });

            modelBuilder.Entity("ProductProductCategory", b =>
                {
                    b.Property<int>("ProductCategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("ProductCategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ProductProductCategory");
                });

            modelBuilder.Entity("ProductShop", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<int>("ShopsId")
                        .HasColumnType("int");

                    b.HasKey("ProductsId", "ShopsId");

                    b.HasIndex("ShopsId");

                    b.ToTable("ProductShop");
                });

            modelBuilder.Entity("BasketProduct", b =>
                {
                    b.HasOne("GameGenesisApi.Models.Basket", null)
                        .WithMany()
                        .HasForeignKey("BasketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameGenesisApi.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameGenesisApi.Models.Account", b =>
                {
                    b.HasOne("GameGenesisApi.Models.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("GameGenesisApi.Models.Account", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameGenesisApi.Models.Basket", b =>
                {
                    b.HasOne("GameGenesisApi.Models.Account", "Account")
                        .WithOne("Basket")
                        .HasForeignKey("GameGenesisApi.Models.Basket", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("GameGenesisApi.Models.Library", b =>
                {
                    b.HasOne("GameGenesisApi.Models.Account", "Account")
                        .WithOne("Library")
                        .HasForeignKey("GameGenesisApi.Models.Library", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("GameGenesisApi.Models.Product", b =>
                {
                    b.HasOne("GameGenesisApi.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LibraryProduct", b =>
                {
                    b.HasOne("GameGenesisApi.Models.Library", null)
                        .WithMany()
                        .HasForeignKey("LibrariesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameGenesisApi.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductProductCategory", b =>
                {
                    b.HasOne("GameGenesisApi.Models.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("ProductCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameGenesisApi.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductShop", b =>
                {
                    b.HasOne("GameGenesisApi.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameGenesisApi.Models.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameGenesisApi.Models.Account", b =>
                {
                    b.Navigation("Basket")
                        .IsRequired();

                    b.Navigation("Library")
                        .IsRequired();
                });

            modelBuilder.Entity("GameGenesisApi.Models.User", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
